#!/bin/sh

set -e

case "$1" in
        configure)
                mkdir -p /var/log/hhvm
                chown www-data.www-data /var/log/hhvm
                chown www-data.www-data /var/www
                chmod 0755 /var/log/hhvm
        ;;

        abort-upgrade|abort-remove|abort-deconfigure)
        ;;

        *)
                echo "postinst called with unknown argument \`$1'" >&2
                exit 1
        ;;
esac

#DEBHELPER#

exit 0

